defaults:
  - data: all_3d
  - data/preprocessing/lighting: polyhaven_source_v0
  - data/preprocessing/rendering: blender_cycles_512
  - _self_

predictions_dir: outputs/pbr_3d/trellis2/predictions
save_rerenders: false
eval_rerendering: true
eval_baking: true
target_envmaps: null
lpips_backbone: alex
device: cpu
model_cache_dir: data/checkpoints/torch
strict: false

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
