defaults:
  - data: all_2d
  - data/lighting: polyhaven_envmaps
  - data/preprocessing/rendering: blender_cycles_512
  - _self_

predictions_dir: outputs/pbr_2d/supermat/predictions
output_file: null
lpips_backbone: alex
device: cpu
model_cache_dir: data/checkpoints/torch
strict: false
workers: 1

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
